-- CREATE TABLES

CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    PRODUCT_PRICE DECIMAL(5,2),
    PRODUCT_DESCRIPTION VARCHAR(100)
);

CREATE TABLE STORE (
    STORE_ID INT PRIMARY KEY,
    STORE_LOCATION CHAR(6),
    STORE_PHONE VARCHAR(15),
    STORE_NAME VARCHAR(50)
);

CREATE TABLE COUPON (
    COUPON_ID INT PRIMARY KEY
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    C_FNAME VARCHAR(50),
    C_LNAME VARCHAR(50),
    C_ADDRESS VARCHAR(100),
    C_PHONE VARCHAR(15)
);

CREATE TABLE `ORDER` (
    ORDER_ID INT PRIMARY KEY,
    ORDER_DATE DATE,
    STORE_ID INT,
    CUSTOMER_ID VARCHAR(20),
    COUPON_ID INT,
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (COUPON_ID) REFERENCES COUPON(COUPON_ID)
);

CREATE TABLE ORDER_ITEM (
    ORDERITEM_ID INT PRIMARY KEY,
    ORDER_ID INT,
    ORDER_QUANTITY INT,
    ORDER_TOTAL DECIMAL(10,2),
    PRODUCT_ID INT,
    FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ORDER_ID)
);

CREATE TABLE EMPLOYEE (
    EID VARCHAR(20) PRIMARY KEY,
    E_FNAME VARCHAR(50),
    E_LNAME VARCHAR(50),
    STORE_ID INT,
    E_ADDRESS VARCHAR(100),
    E_PHONE VARCHAR(15),
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);
